[project]
name = "promising"
version = "0.1.0a1"
description = """\
A new, general-purpose hierarchical async framework for Python, adapted to \
the emerging reality of building highly parallel LLM-based multi-agent \
systems.\
"""
authors = [{name = "Oleksandr Tereshchenko", email = "toporok@gmail.com"}]
readme = "README.md"
license = {text = "MIT"}

requires-python = ">=3.11,<4.0"
dependencies = [
    # # TODO Should we make this dependency optional or mandatory, when json
    # #  serialization is implemented ?
    # "orjson",
]

[project.optional-dependencies]
dev = [
    "hatch",
    "ipython",
    # "jupyterlab",
    # "notebook",  # This is needed for notebooks to work in PyCharm
    "pre-commit",
    "pytest",
    "pytest-asyncio",
    "pytest-cov",
    "pytest-dotenv",
    "pytest-timeout",
    "pytest-xdist",
    "python-dotenv",
    "ruff",
]
examples = [
    "aiohttp",
    "litellm",
    "pydantic",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
asyncio_default_test_loop_scope = "function"
addopts = "-n auto"
timeout = 5
markers = [
    "do_not_patch_qualnames",
    "skip_cycle_detection_gh_issue_66",
    "skip_feature_possibly_obsolete",
]

[tool.coverage.run]
branch = true
source = ["promising"]

[tool.ruff]
line-length = 119
target-version = "py311"

[tool.ruff.lint]
select = ["E", "F", "W", "I", "N", "UP", "B", "C4", "PL"]
ignore = [
    "PLR0913",  # too-many-arguments
]

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = [
    "PLR2004",  # magic-value-comparison
]

[tool.ruff.format]
quote-style = "double"
